# wrangler.toml
name = "gemini-proxy-panel"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "46c514afb166452b83a5266ec1f1c5ee"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "62604e538ba04516a685bbc776d9d677"
